# Generated by Django 5.2.10 on 2026-01-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
